FROM python:3.13.5-alpine3.21

# Installer socat
RUN apk add --no-cache socat
RUN pip install regex  # Pour ajouter timeout sur regex

#Paramètrer le dossier courant de l'utilisateur
WORKDIR /usr/src/app

#Copier les fichiers dans le dossier courant de l'utilisateur
COPY . .

#Lance le script python
CMD socat TCP-LISTEN:9000,reuseaddr,fork EXEC:"python ./hymn-neon.py",pty,stderr